{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "slack-pagerduty-bot.fullname" $ }}-{{ .name }}
spec:
  refreshInterval: {{ .refreshInterval | default "5m" | quote }}
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "slack-pagerduty-bot.fullname" $ }}-{{ .name }}
    creationPolicy: Owner
  {{- if .template }}
    template:
      {{- toYaml .template | nindent 6 }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{- toYaml .dataFrom | nindent 4 }}
  {{- end }}
  {{- if .data }}
  data:
    {{- toYaml .data | nindent 4 }}
  {{- end }}
{{- end }}
