name: "Build and Push Docker Image"
run-name: "Build Docker Image by @${{ github.actor }}"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm-chart/**'
      - '**.md'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: "ghcr.io/comet-ml/slack-pagerduty-bot"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version
        id: build_number
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}" >> $GITHUB_STEP_SUMMARY

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}:${{ steps.build_number.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Git Tag
        run: |
          git config --local user.email "github-actions@comet.com"
          git config --local user.name "GitHub Actions"
          git tag -a v${{ steps.build_number.outputs.version }} -m "Release v${{ steps.build_number.outputs.version }}"
          git push origin v${{ steps.build_number.outputs.version }}

      - name: Build Summary
        run: |
          echo "### Docker images pushed:" >> $GITHUB_STEP_SUMMARY
          echo "${{ env.DOCKER_REGISTRY }}:${{ steps.build_number.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Built for platforms: linux/amd64" >> $GITHUB_STEP_SUMMARY
          echo "Git tag created: v${{ steps.build_number.outputs.version }}" >> $GITHUB_STEP_SUMMARY
