name: "Lint Helm Chart"
run-name: "Lint Helm Chart by @${{ github.actor }}"

on:
  pull_request:
    paths:
      - "helm-chart/**"
  push:
    branches:
      - main
    paths:
      - "helm-chart/**"

jobs:
  lint-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Run lint on Helm chart
        run: |
          set -e
          cd helm-chart
          helm lint --strict .
          echo "✅ Helm chart linting passed" >> $GITHUB_STEP_SUMMARY


